name: Release
on:
  push:
    branches: [ main ]
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml
  release:
    name: Release
    needs: [ checks ]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Java
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: 23
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4.3.1
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          add-job-summary: never
      - name: Release
        run: npx --package=@semantic-release/exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
